services:
  db:
    networks:
      - default

  iam:
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
    environment:
      KC_HOSTNAME: auth.zootopia.chat
    networks:
      - default
      - reverse-proxy
    labels:
      caddy: auth.zootopia.chat

volumes:
  db:
    name: zoot-auth-db

networks:
  reverse-proxy:
    external: true