keycloak_url: https://auth.zootopia.chat

clients:
  - client_id: portainer
    name: Portainer
    authorization_code_flow: true
    redirect_uris:
      - https://portainer.zootopia.chat
    default_client_scopes:
      - "{{ client_scope_zpd }}"
    pkce: false
    pushed_authorization_requests: false

  - client_id: aio
    name: Zootopia AIO
    authorization_code_flow: true
    consent_required: false
    redirect_uris:
      - https://app.zootopia.chat/signin-oidc
    post_logout_redirect_uris:
      - https://app.zootopia.chat/signout-callback-oidc
    jwks_url: https://zootopia.chat/.well-known/jwks
    backchannel_logout_url: https://zootopia.chat/signout-backchannel-oidc
    optional_client_scopes:
      - profile
      - roles

  - client_id: aio-dev
    name: Zootopia AIO (dev)
    authorization_code_flow: true
    consent_required: false
    redirect_uris:
      - https://app.zoot.tawmy.dev/signin-oidc
    post_logout_redirect_uris:
      - https://app.zoot.tawmy.dev/signout-callback-oidc
    jwks_url: https://zoot.tawmy.dev/.well-known/jwks
    backchannel_logout_url: https://zoot.tawmy.dev/signout-backchannel-oidc
    optional_client_scopes:
      - profile
      - roles
