---
- name: Set up Master realm
  ansible.builtin.import_tasks: realm-master/main.yml

- name: Set up Main realm
  ansible.builtin.import_tasks: realm-main/main.yml

- name: Set up authentication flows
  ansible.builtin.import_tasks: authentication-flows/main.yml
