---
- name: Disable account console client
  community.general.keycloak_client:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    state: present
    realm: "{{ keycloak_realm_name }}"
    client_id: account-console
    enabled: false
